app:
    resource: "@AppBundle/Controller/"
    type:     annotation
about:
    path: /about
    defaults: {_controller: AppBundle:Default:about}
home:
    path: /
    defaults: {_controller: AppBundle:Default:index}
add:
    path: /add
    defaults: {_controller: AppBundle:Default:add}
